### PR TITLE
Update visibilityjs.rb

### PR DESCRIPTION
**Pull request by waseems**
Fixed compatibility with Rails 4.2

### CODE REVIEW

**Comment by ai** [comment]
Thanks. But why you remove `install` method?

**Comment by waseems** [comment]
I just found it unnecessary, but perhaps I misunderstood its use case?

-- 
Waseem Sadiq

On 22 Feb 2016 at 14:15:51, Andrey Sitnik (notifications@github.com) wrote:

Thanks. But why you remove install method?

**Comment by ai** [comment]
This method is used in non-Rails Sprokets environments.

Can you fix PR and keep it? 😀

**Comment by waseems** [comment]
Updated the PR

**Comment by ai** [comment]
Released in 1.2.2

**Pull request merged**
